# -- Graphics settings --
# Change the graphical behaviour of the game
# Set a custom resolution of change the magnitude of the shake effect
graphics:
  window: # WARNING: These are not working, likely causing an error on game starting
    width: 800
    height: 600
  render:
    width: 800
    height: 600

  fps: 60 # WARNING: This change the speed of execution of certain game elements
          # TODO: Fix the game to support variable refresh rate

  shake: # Shaders effects configuration
    magnitude: 5
    duration: 10

  ball:
    trail_length: 15

audio:
  volume:
    master: 0.1

# -- Game settings --
# Settings of the level scene
# You can change the ball radius, the speed or the number of initial lives
game:
  player:
    width_multiplier: 10

  ball:
    radius: 10
    speed: 8 # WARNING: This often break collisions with the bricks

  initial_lives: 5

# -- Development Parameters --
# These variables are only used for development purpose
# Here you can set the start scene and change the graphical behaviour and logic of the game
debug:
  shaders: true
  offset: true

  precise_mouse: false

  startup:
    # Set to "default" to disable overwrite
    scene: default

  game:
    infinite_lives: false
    autostart: false
    autoplay: false

  misc:
    error_handler: false
    easter_egg: false

  logs:
    special.all: true
    core.event_manager.event_name: false
    core.event_manager.verbose: false
    systems.renderer: false
    objects.brick.brickgroup.group_verbose: false

engine:
  # -1: No logs
  # 0: Highlight
  # 1: Critical
  # 2: Error
  # 3: Warn
  # 4: Infos, Success
  log_level: 4

release:
  version: "0.1.7"
  state: "BETA"
  compliant_name: "Winter Update"
